### ISSUE TITLE
Get system notified about removal and creation of entity

### ISSUE THREAD

**Issue by Marty** [denniskaselow/dartemis#63]
Hi there and thanks for this neat library :)

I want to build a `System` that can react to the creation and deletion of entities matching the systems `Aspect`.  
Initially I thought (hoped), I just had to implement `EntityObserver` and this would do the trick, but it seems, that this is restricted to `Manager`s.

Now I could implement a `Manager` that does this, but I still need a `System` with the the same `Aspect` that does additional stuff.

I think it would be nice to have for example a mixin on an `EntitySystem` that implicitly enables the call of `onCreate´ and `onRemove`.

Is this something you'd consider, or can I easily implement that behavior myself without too much workarounds?  
I already tried implementing `Manager` in my `System` too, but then it gets initialized twice.

Greetings and merry christmas!

**Comment by denniskaselow** [comment]
> I just had to implement `EntityObserver` and this would do the trick

Oh, I see the API doc on that one is a bit outdated. It was possible in the past, though those methods handled all entities instead of just the ones the system is interested in if my memory serves me right. Things changed a bit since then and it would be a bit more complicated. One thing to consider: would `onCreate`/`onRemove` also receive entities that had received/lost components and are now/no longer handled by the system? Or would I have to (re)introduce a `onChange`/`changed` method on `EntityObserver`?

I think I removed that functionality because I never used it. What is your use case? Maybe there is a better way to achieve the same thing you want to do.

> Is this something you'd consider, or can I easily implement that behavior myself without too much workarounds?

One workaround I can think of is to override the `processEntities` method which receives all entities and store them to create a delta on each call. But that won't work if you need to access data from deleted entities because they either don't exist anymore or have been reused already. Though if you need to, that could be combined with a `Manager` where you store those entities and use the `deleted` method of it if the deleted entity is in the stored entities. At this point you'll still have access to the data of the (to be) deleted entity (unless they only changed and aren't removed from the world and only from the system - changed entities can create quite a rabbit hole).

**Comment by Marty** [comment]
Ah yes, I did not think about entities that have their components changed ... I don't need that but it would be logical to do it that way. 
Your idea with building the delta in `processEntities` sounds good, I will try that.

My use case is that I want to create objects in a game where another object just died / got destroyed. First I thought about creating an entity on the same position upon destruction and having a system that picks that one up.
Now that I think about it, I could also create a component `ToBeRemoved`/`Dead` or something like that, to mark entities that should be removed ...

Thanks for your input, I think I will find a good solution :)

May I ask what your future plans are for dartemis?

**Comment by denniskaselow** [comment]
> Now that I think about it, I could also create a component ToBeRemoved/Dead or something like that, to mark entities that should be removed ...

I think that's something I've done myself in at least one of my games.

> May I ask what your future plans are for dartemis?

I don't really have long term plans. If there are bugs, I fix them. I mostly use it for game jams and often in combination with AngularDart/ngdart so I keep it updated to be compatible with that (this mostly concerns `dartemis_builder`).

But I'm not planning any big changes like Archetypes as in the Java version artemis-odb. 

Once metaprogramming becomes a thing in Dart I'll probably do something for simpler declaration of PooledComponents like I had in the past with `dartemis_transformer`.

As for short term plans, now that you pointed me to the uselessness of `EntityObserver` I may remove that one soon ;). And update some docs that refer to `[int]` instead of `entity`.
